<a href="https://colab.research.google.com/github/Himanshu-kashyap/Pytorch-Tutorials/blob/master/1_NeuralNW_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###imports

In [0]:
import numpy as np
import torch

### sigmoid function

In [0]:
def sigmoid(x):
  return(1/1+np.exp(-x))

### create random data

In [0]:
torch.manual_seed(42)

features = torch.randn((1,5))
wts = torch.randn_like(features)
bias = torch.randn((1,1))


In [11]:
y = sigmoid(torch.sum(features*wts)+bias)
y

tensor([[1.6616]])

In [12]:
y = sigmoid(torch.mm(features,wts.view(5,1))+bias)  # view will convert to desired output
y

tensor([[1.6616]])

In [0]:
# creating 3 inputs 1 hidden layer and 1 output unit

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [14]:
h = sigmoid(torch.mm(features,W1)+B1)
output = sigmoid(torch.mm(h,W2)+B2)
print(output)

tensor([[1.0742]])
